function  FileOutFHtml=createDataSetStatus_FunctionWebPage(WMO,GlobalDS)
% Float web page (NNNNNNN.html). 
% Each figure has a title and a caption, and clicking a figure &
% opens it enlarged (lightbox).

if nargin==1
    GlobalDS.DirOutGraph='./html/floats';
    GlobalDS.DirArgoData='/Users/pvb/Data/Argo';
end

configWebPage

fprintf('web page, ')

%% Read Metada data
MD=createDataSetStatus_FunctionMetadata(WMO,GlobalDS.DirArgoData);

% Initial CTD available? (same test as createDataSetStatus_FunctionFigures)
fileCTD0=fullfile(GlobalDS.DirArgoData,'Floats','CTD',strcat(num2str(WMO),'CTD0.mat'));
TextCTD0='';
if exist(fileCTD0,'file')==2
    TextCTD0=' El cuadrado (mapa) y la línea gris gruesa (diagrama y perfiles) corresponden al perfil CTD realizado durante el despliegue.';
end

%% Figures: file, link (image shown when clicked), title and caption
Fig(1).file=sprintf('%07dA.png',MD.WMOFloat);
Fig(1).link=Fig(1).file;
Fig(1).title='Trayectoria, diagrama θ-S y perfiles verticales';
Fig(1).caption=['Arriba a la izquierda, trayectoria del perfilador: el color de cada posición indica la fecha del perfil (barra de color) ', ...
    'y las líneas grises son las isóbatas de 1000, 2000 y 4000 m. ', ...
    'Arriba a la derecha, diagrama temperatura potencial - salinidad de todos los perfiles, con las isopicnas (σ<sub>0</sub>) en gris. Los puntos grises son los valores históricos. ', ...
    'Abajo, perfiles verticales de temperatura potencial, salinidad y, si el perfilador dispone de sensor, oxígeno disuelto. ', ...
    'En todos los paneles el color indica la fecha del perfil y el último perfil se resalta en negro.',TextCTD0];

Fig(2).file=sprintf('%07dB.png',MD.WMOFloat);
Fig(2).link=Fig(2).file;
Fig(2).title='Evolución temporal de la temperatura y la salinidad';
Fig(2).caption=['Temperatura (arriba) y salinidad (abajo) medidas por el perfilador en función de la fecha (eje horizontal) y de la presión (eje vertical). ', ...
    'Para cada variable, el panel superior muestra la capa superficial con la escala vertical ampliada y el inferior el resto de la columna de agua. ', ...
    'Las líneas grises son isolíneas y entre corchetes se indican los valores mínimo y máximo medidos.'];

Fig(3).file=sprintf('%07dC.png',MD.WMOFloat);
Fig(3).link=Fig(3).file;
Fig(3).title='Datos técnicos';
Fig(3).caption=['Evolución, en función del número de ciclo, de algunos parámetros técnicos transmitidos por el perfilador: ', ...
    'voltaje de la batería (arriba), offset de presión en superficie (centro) y vacío interno (abajo). ', ...
    'Solo se representan las variables que transmite cada modelo de perfilador.'];

%% Trajectory for the interactive map (Leaflet). Data are embedded in the page
% as [lat, lon, cycle, date, color]; color by date with the same colormap
% (parula) used in the trajectory figure.
FloatData=load(fullfile(GlobalDS.DirArgoData,'Floats',num2str(WMO)),'HIDf');
lon=FloatData.HIDf.lons(:);
lat=FloatData.HIDf.lats(:);
julds=FloatData.HIDf.julds(:);
cycle=FloatData.HIDf.cycle(:);
ind=find(isnan(lon)==0 & isnan(lat)==0);
[~,iSort]=sort(julds(ind)); % chronological order (some floats have descending and ascending profiles)
ind=ind(iSort);
lon=lon(ind); lat=lat(ind); julds=julds(ind); cycle=cycle(ind);
cl=parula;
iColor=ceil(linspace(1,size(cl,1),numel(lon)));
TrayectoriaJS=cell(numel(lon),1);
for ii=1:numel(lon)
    TrayectoriaJS{ii}=sprintf('[%.4f,%.4f,%d,"%s","#%02x%02x%02x"]',lat(ii),lon(ii),cycle(ii), ...
        datestr(julds(ii),'dd-mmm-yyyy'),round(255*cl(iColor(ii),:)));
end
TrayectoriaJS=['[' strjoin(TrayectoriaJS,',') ']'];
GradienteJS=strjoin(arrayfun(@(k) sprintf('#%02x%02x%02x',round(255*cl(k,:))),round(linspace(1,size(cl,1),8)),'UniformOutput',false),',');

%% Rows of the metadata table {label, value, label, value}
Tabla={ ...
    'Transmission system',         MD.TransmisionSystem, 'Transmission ID',         MD.TransmissionID; ...
    'Platform model',              MD.PlatformModel,     'Platform ID',             MD.PlatformID; ...
    'Sensors',                     MD.Sensors,           'Sensores s/n',            MD.SensorsID; ...
    'Data Centre (Format version)',MD.DataCentre,        'Project name',            MD.ProjectName; ...
    'Float Owner',                 MD.FloatOwner,        'PI Name',                 MD.PIName; ...
    'Parking depth (dbar)',        MD.ParkingDepth,      'Profile depth (dbar)',    MD.ProfileDepth; ...
    'Number of profiles',          MD.NumberOfProfiles,  'Status',                  MD.StatusT; ...
    'Deployment date',             MD.LaunchDate,        'Deployed position',       MD.LaunchPosition; ...
    'Last surfacing date',         MD.LastSurfacingDate, 'Last surfacing position', MD.LastSurfacingPosition; ...
    'Age (Yr)',                    MD.Age,               MD.VoltageT,               MD.Voltage};
if isempty(MD.SurfacePressure) == 0 & isempty(MD.InternalVacum)
    Tabla(end+1,:)={MD.SurfacePressureT, MD.SurfacePressure, MD.InternalVacumT, MD.InternalVacum};
end

%% Institutional logos
Logos='';
if strfind(lower(MD.ProjectName),'spain')>=1 | strfind(lower(MD.FloatOwner),'ieo')>=1 | strfind(lower(MD.FloatOwner),'socib')>=1 | strfind(lower(MD.FloatOwner),'csic')>=1 | strfind(lower(MD.FloatOwner),'icm')>=1  | strfind(lower(MD.FloatOwner),'icatmar')>=1
    Logos=['<a href="http://www.ieo.es"><img src="https://www.argoespana.es/imagenes/logoieo.png" alt="IEO"></a>', ...
        '<a href="http://www.socib.es"><img src="https://www.argoespana.es/imagenes/logosocib.png" alt="SOCIB"></a>'];
    if strfind(MD.FloatOwner,'ICATMAR')>=1
        Logos=[Logos '<a href="http://www.icatmar.cat/es"><img src="https://www.argoespana.es/imagenes/logoicatmar.png" alt="ICATMAR"></a>'];
    end
end

%% Escribe pagina web
FileOutFHtml=sprintf('%s/%07d.html',GlobalDS.DirOutGraph,WMO);
fid = fopen(FileOutFHtml,'w','n','UTF-8');
fprintf(fid,'%s\n', ...
    '<!DOCTYPE html>', ...
    '<html lang="es">', ...
    '<head>', ...
    sprintf('<title>Argo España %07d</title>',MD.WMOFloat), ...
    '<meta charset="utf-8">', ...
    '<meta name="viewport" content="width=device-width, initial-scale=1">', ...
    '<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">', ...
    '<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>', ...
    '<link rel="stylesheet" href="https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css">', ...
    '<script src="https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js"></script>', ...
    '<style type="text/css">', ...
    'body {margin: 0; background: #ffffff; font-family: verdana, sans-serif; color: #0c2046;}', ...
    'a {color: #0c2046;}', ...
    '.container {max-width: 1000px; margin: 0 auto; padding: 1.5em 16px;}', ...
    '.cabecera {display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1em;}', ...
    '.cabecera a {max-width: 100%;}', ...
    '.cabecera img {border: 0; max-width: 100%; height: auto;}', ...
    '.logos a {margin-left: 1.2em;}', ...
    '.logos-pie {text-align: center; margin: 2em 0 1em;}', ...
    '.logos-pie a {margin: 0 0.6em;}', ...
    '.logos-pie img, .logos img {border: 0;}', ...
    'h1 {font-size: 30px; font-weight: bold; text-align: center; margin: 1.5em 0 0.6em;}', ...
    '.enlaces {text-align: center; font-size: 20px; font-weight: bold; line-height: 2em; margin-bottom: 1.5em;}', ...
    '.tabla {overflow-x: auto; margin-bottom: 2em;}', ...
    '.tabla table {width: 100%; border-collapse: separate; border-spacing: 2px;}', ...
    '.tabla td {height: 25px; padding: 0 0.6em; font-size: 12px; text-align: left;}', ...
    '.tabla td.etiqueta {background: #e5e5e5; font-weight: bold; color: #0c2046; width: 25%;}', ...
    '.tabla td.valor {font-weight: normal; color: #000000; width: 25%;}', ...
    '.figura {margin: 0 0 2.5em;}', ...
    '.figura img {display: block; width: 100%; height: auto; border: 0; cursor: zoom-in;}', ...
    '.pie {border: 1px solid #bebebe; padding: 0.8em 1em;}', ...
    '.pie h3 {font-size: 12px; font-weight: bold; color: #0c2046; margin: 0 0 0.4em;}', ...
    '.pie p {font-size: 12px; font-weight: normal; color: #333333; line-height: 1.5em; text-align: justify; margin: 0;}', ...
    '.actualizacion {text-align: right; font-size: 10px; color: #0c2046;}', ...
    '#lightbox {display: none; position: fixed; inset: 0; z-index: 1000; background: rgba(0,0,0,0.85); align-items: center; justify-content: center;}', ...
    '#lightbox.active {display: flex;}', ...
    '#lightbox img {max-width: 95vw; max-height: 95vh; background: #ffffff;}', ...
    '#lightbox button {position: absolute; top: 0.3em; right: 0.6em; font-size: 2.5em; color: #ffffff; background: none; border: 0; cursor: pointer;}', ...
    '#mapa {position: relative; width: 100%; height: 480px; touch-action: pan-y;}', ...
    '.mapa-aviso {position: absolute; inset: 0; z-index: 400; display: flex; align-items: center; justify-content: center; background: rgba(0,0,0,0.15); color: #ffffff; font: bold 14px verdana, sans-serif; text-shadow: 0 1px 2px rgba(0,0,0,0.6); pointer-events: none;}', ...
    '.mapa-leyenda {background: rgba(255,255,255,0.92); padding: 6px 8px; border-radius: 5px; font: 11px verdana, sans-serif; color: #0c2046; box-shadow: 0 0 10px rgba(0,0,0,0.2);}', ...
    '.mapa-leyenda .barra {width: 150px; height: 10px; margin: 4px 0 2px;}', ...
    '.mapa-leyenda .fechas {display: flex; justify-content: space-between;}', ...
    '@media (max-width: 767px) {#mapa {height: 360px;}}', ...
    '</style>', ...
    '</head>', ...
    '<body>', ...
    '<div class="container">');

% Cabecera
fprintf(fid,'%s\n', ...
    '<div class="cabecera">', ...
    '<a href="https://www.argoespana.es/"><img src="https://www.argoespana.es/imagenes/logoargoes.png" alt="Argo España"></a>', ...
    ['<div class="logos">' Logos '</div>'], ...
    '</div>');

% Titulo y enlaces
fprintf(fid,'<h1>Perfilador Argo %7d</h1>\n',MD.WMOFloat);
fprintf(fid,'<div class="enlaces">\n');
fprintf(fid,'<a href="https://fleetmonitoring.euro-argo.eu/float/%7d">Acceso a los datos</a><br>\n',MD.WMOFloat);
fileReport=fullfile(GlobalDS.DirArgoData,'Floats','Informes',strcat(num2str(WMO),'InformeLanzamiento.pdf'));
if exist(fileReport,'file')==2
    fprintf(fid,'<a href="%s/Informes/%7dInformeLanzamiento.pdf">Informe de despliegue</a><br>\n',domainName,MD.WMOFloat);
end
fileReport=fullfile(GlobalDS.DirArgoData,'Floats','Informes',strcat(num2str(WMO),'InformeDMQC.pdf'));
if exist(fileReport,'file')==2
    fprintf(fid,'<a href="%s/Informes/%7dInformeDMQC.pdf">Informe de Delayed Mode Quality Control</a><br>\n',domainName,MD.WMOFloat);
end
fprintf(fid,'</div>\n');

% Tabla con informacion
fprintf(fid,'<div class="tabla"><table>\n');
for ii=1:size(Tabla,1)
    fprintf(fid,'<tr><td class="etiqueta">%s</td><td class="valor">%s</td><td class="etiqueta">%s</td><td class="valor">%s</td></tr>\n',Tabla{ii,:});
end
fprintf(fid,'</table></div>\n');

% Mapa interactivo de la trayectoria (Leaflet)
if ~isempty(lon)
    fprintf(fid,'%s\n', ...
        '<div class="figura">', ...
        '<div id="mapa"></div>', ...
        '<div class="pie">', ...
        '<h3>Mapa interactivo de la trayectoria</h3>', ...
        ['<p>Posiciones de todos los perfiles realizados por el perfilador. El color indica la fecha del perfil (misma escala que la figura de la trayectoria), ', ...
        'el círculo con borde blanco es la posición de despliegue y el de borde negro la última posición. ', ...
        'Pinche en el mapa para activar el zoom y el desplazamiento, y en cada posición para ver el número de ciclo y la fecha.</p>'], ...
        '</div>', ...
        '</div>', ...
        '<script>', ...
        ['var trayectoria = ' TrayectoriaJS ';'], ...
        ['var gradiente = "' GradienteJS '";'], ...
        'var mapa = L.map("mapa", {scrollWheelZoom: false, dragging: false, touchZoom: false, doubleClickZoom: false, fullscreenControl: true});', ...
        'mapa.attributionControl.setPrefix("<a href=\"https://leafletjs.com\">Leaflet</a>");', ...
        'var esri = "https://server.arcgisonline.com/ArcGIS/rest/services/";', ...
        'var capas = {', ...
        '  "Batimetría": L.tileLayer(esri + "Ocean/World_Ocean_Base/MapServer/tile/{z}/{y}/{x}", {attribution: "Tiles &copy; Esri", maxZoom: 13}),', ...
        '  "Satélite": L.tileLayer(esri + "World_Imagery/MapServer/tile/{z}/{y}/{x}", {attribution: "Tiles &copy; Esri"})', ...
        '};', ...
        'capas["Batimetría"].addTo(mapa);', ...
        'L.control.layers(capas, null, {position: "topleft"}).addTo(mapa);', ...
        'L.control.scale({imperial: false}).addTo(mapa);', ...
        'var puntos = trayectoria.map(function(p){ return [p[0], p[1]]; });', ...
        'L.polyline(puntos, {color: "#555555", weight: 1, opacity: 0.8}).addTo(mapa);', ...
        'trayectoria.forEach(function(p, i){', ...
        '  var extremo = (i === 0 || i === trayectoria.length - 1);', ...
        '  L.circleMarker([p[0], p[1]], {radius: extremo ? 7 : 4, color: i === 0 ? "#ffffff" : (extremo ? "#000000" : p[4]), weight: extremo ? 2 : 1, fillColor: p[4], fillOpacity: 0.9})', ...
        '   .bindPopup("<b>Ciclo " + p[2] + "</b><br>" + p[3] + "<br>" + p[0].toFixed(3) + "&deg;N, " + p[1].toFixed(3) + "&deg;E")', ...
        '   .addTo(mapa);', ...
        '});', ...
        'mapa.fitBounds(L.latLngBounds(puntos).pad(0.15), {maxZoom: 8});', ...
        'var leyenda = L.control({position: "bottomright"});', ...
        'leyenda.onAdd = function(){', ...
        '  var div = L.DomUtil.create("div", "mapa-leyenda");', ...
        '  div.innerHTML = "<b>Fecha del perfil</b><div class=\"barra\" style=\"background: linear-gradient(to right," + gradiente + ")\"></div>" +', ...
        '    "<div class=\"fechas\"><span>" + trayectoria[0][3] + "</span><span>" + trayectoria[trayectoria.length - 1][3] + "</span></div>";', ...
        '  return div;', ...
        '};', ...
        'leyenda.addTo(mapa);', ...
        '// Interaccion: click (o dos dedos en movil) activa el mapa; al salir se desactiva', ...
        'var contenedor = mapa.getContainer();', ...
        'var aviso = document.createElement("div");', ...
        'aviso.className = "mapa-aviso";', ...
        'aviso.textContent = window.innerWidth <= 767 ? "Usa dos dedos para mover el mapa" : "Haz click para activar el mapa";', ...
        'contenedor.appendChild(aviso);', ...
        'function activa(){ mapa.dragging.enable(); mapa.touchZoom.enable(); mapa.scrollWheelZoom.enable(); mapa.doubleClickZoom.enable(); aviso.style.display = "none"; }', ...
        'function desactiva(){ mapa.dragging.disable(); mapa.touchZoom.disable(); mapa.scrollWheelZoom.disable(); mapa.doubleClickZoom.disable(); aviso.style.display = "flex"; }', ...
        'mapa.on("click", activa);', ...
        'contenedor.addEventListener("mouseleave", function(){ if(!mapa.isFullscreen || !mapa.isFullscreen()){ desactiva(); } });', ...
        'mapa.on("fullscreenchange", function(){ if(mapa.isFullscreen()){ activa(); } });', ...
        'var temporizador;', ...
        'contenedor.addEventListener("touchstart", function(e){ if(e.touches.length === 2){ clearTimeout(temporizador); activa(); } });', ...
        'contenedor.addEventListener("touchend", function(){ clearTimeout(temporizador); temporizador = setTimeout(desactiva, 800); });', ...
        '</script>');
end

% Figuras con pie
for ii=1:length(Fig)
    fprintf(fid,'%s\n', ...
        '<div class="figura">', ...
        sprintf('<a href="./%s"><img src="./%s" alt="%s"></a>',Fig(ii).link,Fig(ii).file,Fig(ii).title), ...
        '<div class="pie">', ...
        sprintf('<h3>%s</h3>',Fig(ii).title), ...
        sprintf('<p>%s</p>',Fig(ii).caption), ...
        '</div>', ...
        '</div>');
end

% Logos y actualizacion
if ~isempty(Logos)
    fprintf(fid,'<div class="logos-pie">%s</div>\n',Logos);
end
fprintf(fid,'<div class="actualizacion">%s</div>\n', datestr(now));
fprintf(fid,'</div>\n');

% Lightbox: al pinchar en una figura se muestra ampliada
fprintf(fid,'%s\n', ...
    '<div id="lightbox"><button id="lightbox-close" aria-label="Cerrar">&times;</button><img id="lightbox-img" src="" alt=""></div>', ...
    '<script>', ...
    'document.addEventListener("DOMContentLoaded", function(){', ...
    '  var lb = document.getElementById("lightbox");', ...
    '  var lbImg = document.getElementById("lightbox-img");', ...
    '  document.querySelectorAll(".figura > a").forEach(function(link){', ...
    '    link.addEventListener("click", function(e){', ...
    '      e.preventDefault();', ...
    '      lbImg.src = link.getAttribute("href");', ...
    '      lbImg.alt = link.querySelector("img").alt;', ...
    '      lb.classList.add("active");', ...
    '    });', ...
    '  });', ...
    '  function cierra(){ lb.classList.remove("active"); lbImg.src = ""; }', ...
    '  lb.addEventListener("click", function(e){ if(e.target !== lbImg){ cierra(); } });', ...
    '  document.addEventListener("keydown", function(e){ if(e.key === "Escape"){ cierra(); } });', ...
    '});', ...
    '</script>', ...
    '</body>', ...
    '</html>');
fclose(fid);
