function  FileOutFHtml=createDataSetStatus_FunctionWebPage(WMO,GlobalDS)
% Float web page (NNNNNNN.html). 
% Each figure has a title and a caption, and clicking a figure &
% opens it enlarged (lightbox).

if nargin==1
    GlobalDS.DirOutGraph='./html/floats';
    GlobalDS.DirArgoData='/Users/pvb/Data/Argo';
end

configWebPage

fprintf('web page, ')

%% Read Metada data
MD=createDataSetStatus_FunctionMetadata(WMO,GlobalDS.DirArgoData);

% Initial CTD available? (same test as createDataSetStatus_FunctionFigures)
fileCTD0=fullfile(GlobalDS.DirArgoData,'Floats','CTD',strcat(num2str(WMO),'CTD0.mat'));
TextCTD0='';
if exist(fileCTD0,'file')==2
    TextCTD0=' El cuadrado (mapa) y la línea gris gruesa (diagrama y perfiles) corresponden al perfil CTD realizado durante el despliegue.';
end

%% Figures: file, link (image shown when clicked), title and caption
Fig(1).file=sprintf('%07dA.png',MD.WMOFloat);
Fig(1).link=sprintf('%07dA_Zoom.png',MD.WMOFloat);
Fig(1).title='Trayectoria, diagrama θ-S y perfiles verticales';
Fig(1).caption=['Arriba a la izquierda, trayectoria del perfilador: el color de cada posición indica la fecha del perfil (barra de color) ', ...
    'y las líneas grises son las isóbatas de 1000, 2000 y 4000 m. ', ...
    'Arriba a la derecha, diagrama temperatura potencial - salinidad de todos los perfiles, con las isopicnas (σ<sub>0</sub>) en gris. Los puntos grises son los valores históricos. ', ...
    'Abajo, perfiles verticales de temperatura potencial, salinidad y, si el perfilador dispone de sensor, oxígeno disuelto. ', ...
    'En todos los paneles el color indica la fecha del perfil y el último perfil se resalta en negro.',TextCTD0, ...
    ' Pinche en la figura para ver el detalle de la trayectoria reciente.'];

Fig(2).file=sprintf('%07dB.png',MD.WMOFloat);
Fig(2).link=Fig(2).file;
Fig(2).title='Evolución temporal de la temperatura y la salinidad';
Fig(2).caption=['Temperatura (arriba) y salinidad (abajo) medidas por el perfilador en función de la fecha (eje horizontal) y de la presión (eje vertical). ', ...
    'Para cada variable, el panel superior muestra la capa superficial con la escala vertical ampliada y el inferior el resto de la columna de agua. ', ...
    'Las líneas grises son isolíneas y entre corchetes se indican los valores mínimo y máximo medidos.'];

Fig(3).file=sprintf('%07dC.png',MD.WMOFloat);
Fig(3).link=Fig(3).file;
Fig(3).title='Datos técnicos';
Fig(3).caption=['Evolución, en función del número de ciclo, de algunos parámetros técnicos transmitidos por el perfilador: ', ...
    'voltaje de la batería (arriba), offset de presión en superficie (centro) y vacío interno (abajo). ', ...
    'Solo se representan las variables que transmite cada modelo de perfilador.'];

%% Rows of the metadata table {label, value, label, value}
Tabla={ ...
    'Transmission system',         MD.TransmisionSystem, 'Transmission ID',         MD.TransmissionID; ...
    'Platform model',              MD.PlatformModel,     'Platform ID',             MD.PlatformID; ...
    'Sensors',                     MD.Sensors,           'Sensores s/n',            MD.SensorsID; ...
    'Data Centre (Format version)',MD.DataCentre,        'Project name',            MD.ProjectName; ...
    'Float Owner',                 MD.FloatOwner,        'PI Name',                 MD.PIName; ...
    'Parking depth (dbar)',        MD.ParkingDepth,      'Profile depth (dbar)',    MD.ProfileDepth; ...
    'Number of profiles',          MD.NumberOfProfiles,  'Status',                  MD.StatusT; ...
    'Deployment date',             MD.LaunchDate,        'Deployed position',       MD.LaunchPosition; ...
    'Last surfacing date',         MD.LastSurfacingDate, 'Last surfacing position', MD.LastSurfacingPosition; ...
    'Age (Yr)',                    MD.Age,               MD.VoltageT,               MD.Voltage};
if isempty(MD.SurfacePressure) == 0 & isempty(MD.InternalVacum)
    Tabla(end+1,:)={MD.SurfacePressureT, MD.SurfacePressure, MD.InternalVacumT, MD.InternalVacum};
end

%% Institutional logos
Logos='';
if strfind(lower(MD.ProjectName),'spain')>=1 | strfind(lower(MD.FloatOwner),'ieo')>=1 | strfind(lower(MD.FloatOwner),'socib')>=1 | strfind(lower(MD.FloatOwner),'csic')>=1 | strfind(lower(MD.FloatOwner),'icm')>=1  | strfind(lower(MD.FloatOwner),'icatmar')>=1
    Logos=['<a href="http://www.ieo.es"><img src="https://www.argoespana.es/imagenes/logoieo.png" alt="IEO"></a>', ...
        '<a href="http://www.socib.es"><img src="https://www.argoespana.es/imagenes/logosocib.png" alt="SOCIB"></a>'];
    if strfind(MD.FloatOwner,'ICATMAR')>=1
        Logos=[Logos '<a href="http://www.icatmar.cat/es"><img src="https://www.argoespana.es/imagenes/logoicatmar.png" alt="ICATMAR"></a>'];
    end
end

%% Escribe pagina web
FileOutFHtml=sprintf('%s/%07d.html',GlobalDS.DirOutGraph,WMO);
fid = fopen(FileOutFHtml,'w','n','UTF-8');
fprintf(fid,'%s\n', ...
    '<!DOCTYPE html>', ...
    '<html lang="es">', ...
    '<head>', ...
    sprintf('<title>Argo España %07d</title>',MD.WMOFloat), ...
    '<meta charset="utf-8">', ...
    '<meta name="viewport" content="width=device-width, initial-scale=1">', ...
    '<style type="text/css">', ...
    'body {margin: 0; background: #ffffff; font-family: verdana, sans-serif; color: #0c2046;}', ...
    'a {color: #0c2046;}', ...
    '.container {max-width: 1000px; margin: 0 auto; padding: 1.5em 16px;}', ...
    '.cabecera {display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1em;}', ...
    '.cabecera a {max-width: 100%;}', ...
    '.cabecera img {border: 0; max-width: 100%; height: auto;}', ...
    '.logos a {margin-left: 1.2em;}', ...
    '.logos-pie {text-align: center; margin: 2em 0 1em;}', ...
    '.logos-pie a {margin: 0 0.6em;}', ...
    '.logos-pie img, .logos img {border: 0;}', ...
    'h1 {font-size: 30px; font-weight: bold; text-align: center; margin: 1.5em 0 0.6em;}', ...
    '.enlaces {text-align: center; font-size: 20px; font-weight: bold; line-height: 2em; margin-bottom: 1.5em;}', ...
    '.tabla {overflow-x: auto; margin-bottom: 2em;}', ...
    '.tabla table {width: 100%; border-collapse: separate; border-spacing: 2px;}', ...
    '.tabla td {height: 25px; padding: 0 0.6em; font-size: 12px; text-align: left;}', ...
    '.tabla td.etiqueta {background: #e5e5e5; font-weight: bold; color: #0c2046; width: 25%;}', ...
    '.tabla td.valor {font-weight: normal; color: #000000; width: 25%;}', ...
    '.figura {margin: 0 0 2.5em;}', ...
    '.figura img {display: block; width: 100%; height: auto; border: 0; cursor: zoom-in;}', ...
    '.pie {border: 1px solid #bebebe; padding: 0.8em 1em;}', ...
    '.pie h3 {font-size: 12px; font-weight: bold; color: #0c2046; margin: 0 0 0.4em;}', ...
    '.pie p {font-size: 12px; font-weight: normal; color: #333333; line-height: 1.5em; text-align: justify; margin: 0;}', ...
    '.actualizacion {text-align: right; font-size: 10px; color: #0c2046;}', ...
    '#lightbox {display: none; position: fixed; inset: 0; z-index: 1000; background: rgba(0,0,0,0.85); align-items: center; justify-content: center;}', ...
    '#lightbox.active {display: flex;}', ...
    '#lightbox img {max-width: 95vw; max-height: 95vh; background: #ffffff;}', ...
    '#lightbox button {position: absolute; top: 0.3em; right: 0.6em; font-size: 2.5em; color: #ffffff; background: none; border: 0; cursor: pointer;}', ...
    '</style>', ...
    '</head>', ...
    '<body>', ...
    '<div class="container">');

% Cabecera
fprintf(fid,'%s\n', ...
    '<div class="cabecera">', ...
    '<a href="https://www.argoespana.es/"><img src="https://www.argoespana.es/imagenes/logoargoes.png" alt="Argo España"></a>', ...
    ['<div class="logos">' Logos '</div>'], ...
    '</div>');

% Titulo y enlaces
fprintf(fid,'<h1>Perfilador Argo %7d</h1>\n',MD.WMOFloat);
fprintf(fid,'<div class="enlaces">\n');
fprintf(fid,'<a href="https://fleetmonitoring.euro-argo.eu/float/%7d">Acceso a los datos</a><br>\n',MD.WMOFloat);
fileReport=fullfile(GlobalDS.DirArgoData,'Floats','Informes',strcat(num2str(WMO),'InformeLanzamiento.pdf'));
if exist(fileReport,'file')==2
    fprintf(fid,'<a href="%s/Informes/%7dInformeLanzamiento.pdf">Informe de despliegue</a><br>\n',domainName,MD.WMOFloat);
end
fileReport=fullfile(GlobalDS.DirArgoData,'Floats','Informes',strcat(num2str(WMO),'InformeDMQC.pdf'));
if exist(fileReport,'file')==2
    fprintf(fid,'<a href="%s/Informes/%7dInformeDMQC.pdf">Informe de Delayed Mode Quality Control</a><br>\n',domainName,MD.WMOFloat);
end
fprintf(fid,'</div>\n');

% Tabla con informacion
fprintf(fid,'<div class="tabla"><table>\n');
for ii=1:size(Tabla,1)
    fprintf(fid,'<tr><td class="etiqueta">%s</td><td class="valor">%s</td><td class="etiqueta">%s</td><td class="valor">%s</td></tr>\n',Tabla{ii,:});
end
fprintf(fid,'</table></div>\n');

% Figuras con pie
for ii=1:length(Fig)
    fprintf(fid,'%s\n', ...
        '<div class="figura">', ...
        sprintf('<a href="./%s"><img src="./%s" alt="%s"></a>',Fig(ii).link,Fig(ii).file,Fig(ii).title), ...
        '<div class="pie">', ...
        sprintf('<h3>%s</h3>',Fig(ii).title), ...
        sprintf('<p>%s</p>',Fig(ii).caption), ...
        '</div>', ...
        '</div>');
end

% Logos y actualizacion
if ~isempty(Logos)
    fprintf(fid,'<div class="logos-pie">%s</div>\n',Logos);
end
fprintf(fid,'<div class="actualizacion">%s</div>\n', datestr(now));
fprintf(fid,'</div>\n');

% Lightbox: al pinchar en una figura se muestra ampliada
fprintf(fid,'%s\n', ...
    '<div id="lightbox"><button id="lightbox-close" aria-label="Cerrar">&times;</button><img id="lightbox-img" src="" alt=""></div>', ...
    '<script>', ...
    'document.addEventListener("DOMContentLoaded", function(){', ...
    '  var lb = document.getElementById("lightbox");', ...
    '  var lbImg = document.getElementById("lightbox-img");', ...
    '  document.querySelectorAll(".figura a").forEach(function(link){', ...
    '    link.addEventListener("click", function(e){', ...
    '      e.preventDefault();', ...
    '      lbImg.src = link.getAttribute("href");', ...
    '      lbImg.alt = link.querySelector("img").alt;', ...
    '      lb.classList.add("active");', ...
    '    });', ...
    '  });', ...
    '  function cierra(){ lb.classList.remove("active"); lbImg.src = ""; }', ...
    '  lb.addEventListener("click", function(e){ if(e.target !== lbImg){ cierra(); } });', ...
    '  document.addEventListener("keydown", function(e){ if(e.key === "Escape"){ cierra(); } });', ...
    '});', ...
    '</script>', ...
    '</body>', ...
    '</html>');
fclose(fid);
